- hosts: testserver
  become: true
  become_user: root
  tasks:
  - name: install tomcat
    yum: name=tomcat state=present
  - name: start tomcat
    service: name=tomcat state=started
  - name: install git
    yum: name=git state=present
  - name: get repo
    git: repo=https://github.com/Ashish-Rawat-hub/Devops-project1.git dest=/tmp/gitrepo force=yes
  - name: install docker
    yum: name=docker state=present
  - name: start docker
    service: name=docker state=started
